name: Workflow CI

on:
  push:
    branches: [ main ]

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: base
          auto-activate-base: true

      - name: Install MLflow CLI (global)
        run: |
          conda install -y pip
          pip install mlflow

      - name: Run MLflow project with Conda
        run: |
          mlflow run ./MLProject -P n_estimators=150 -P max_depth=15

      - name: Get latest MLflow run_id
        id: get_run
        run: |
          RUN_ID=$(find mlruns/0 -mindepth 1 -maxdepth 1 -type d -printf "%f\n" | grep -E '^[a-f0-9]{32}$' | sort | tail -n 1)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_OUTPUT
          echo "Latest run_id: $RUN_ID"

      - name: Copy MLflow artifacts
        run: |
          mkdir -p temp-artifacts
          cp -r mlruns/0/$RUN_ID/artifacts/* temp-artifacts/

      - name: Push model artifacts to model-artifacts branch
        run: |
          cd temp-artifacts
          git init
          git checkout --orphan model-artifacts
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Add MLflow model artifacts"
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push --force origin model-artifacts
