name: Workflow CI

on: 
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.7

      - name: Install Dependencies
        run: pip install mlflow

      - name: Train model
        run: |
          mlflow run MLProject

      - name: Find latest registered model artifacts
        id: find_model
        run: |
          MODEL_DIR=$(find mlruns/0/models -maxdepth 1 -type d -name "m-*" | sort | tail -n 1)
          echo "Found model directory: $MODEL_DIR"
          echo "MODEL_DIR=$MODEL_DIR" >> $GITHUB_OUTPUT
          
      - name: Copy model artifacts
        run: |
          mkdir -p temp-artifacts
          cp -r "$MODEL_DIR/artifacts" temp-artifacts/

      - name: Upload model to GitHub branch (model-artifacts)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          mkdir temp-artifacts
          cp model.pkl temp-artifacts/

          cd temp-artifacts
          git init
          git checkout --orphan model-artifacts
          git add .
          git commit -m "Add MLflow model artifact from CI"
          git push --force https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:model-artifacts